name: Build and Package [Debug] [master]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_MAIN: ./src/Plaid/Plaid.csproj
  PROJECT_TESTS: ./tests/Plaid.MSTest/Plaid.MSTest.csproj
  BUILD_CONFIGURATION: Debug

jobs:
  
  env-setup:
    runs-on: windows-latest
    steps:
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.1
      - name: Setup .NET Core v3.1
        uses: actions/setup-dotnet@v1.5.0
        with:
          dotnet-version: 3.1.301
      - name: Install-Module PowerShellGet
        run: Install-Module -Name PowerShellGet -Force
  
  build:
    needs: [env-setup]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: dotnet restore $env:PROJECT_MAIN
      - name: Build
        run: dotnet build --configuration $env:BUILD_CONFIGURATION --no-restore $env:PROJECT_MAIN
      
  test:
    needs: [build]
    runs-on: windows-latest
    steps:
      - name: Install Dependencies
        run: dotnet restore $env:PROJECT_TESTS
      - name: Test
        run: dotnet test --configuration $env:BUILD_CONFIGURATION --verbosity normal --no-restore $env:PROJECT_TESTS

  package:
    needs: [test]
    runs-on: windows-latest
    steps:
      - name: Package
        run: dotnet pack --configuration $env:BUILD_CONFIGURATION $env:PROJECT_MAIN
