name: Build and Package [Debug] [master]

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PROJECT_BIN: src/Plaid/bin
  PROJECT_MAIN: src/Plaid/Plaid.csproj
  PROJECT_TESTS: tests/Plaid.MSTest/Plaid.MSTest.csproj
  BUILD_CONFIGURATION: Debug

jobs:
  
  env-setup:
    runs-on: windows-latest
    steps:
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.1
      - name: Setup .NET Core v3.1
        uses: actions/setup-dotnet@v1.5.0
        with:
          dotnet-version: 3.1.301
      - name: Install-Module PowerShellGet
        run: Install-Module -Name PowerShellGet -Force

  build:
    needs: [env-setup]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Extract Project Metadata
        run: |
          [xml]$xml = Get-Content $env:PROJECT_MAIN;
          $val = $xml.SelectNodes('//PropertyGroup/AssemblyName') | Select-Object -Expand '#text'
          echo "::set-env name=ASSEMBLY_NAME::$($val)"
          $val = $xml.SelectNodes('//PropertyGroup/AssemblyVersion') | Select-Object -Expand '#text'
          echo "::set-env name=ASSEMBLY_VERSION::$($val)"
      - name: Build
        run: dotnet build --configuration $env:BUILD_CONFIGURATION $env:PROJECT_MAIN
      - name: Upload Build Output Artifact
        uses: actions/upload-artifact@v2.1.3
        with:
          # Artifact name
          name: Plaid.${{ env.BUILD_CONFIGURATION }}
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ env.PROJECT_BIN }}/${{ env.BUILD_CONFIGURATION }}/netstandard2.0/**/*
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
#      - name: Test
#        run: dotnet test --configuration $env:BUILD_CONFIGURATION --verbosity normal $env:PROJECT_TESTS
      - name: Package
        run: dotnet pack --include-source --include-symbols --configuration $env:BUILD_CONFIGURATION $env:PROJECT_MAIN --verbosity normal
      - name: Upload NuGet Package Artifact
        uses: actions/upload-artifact@v2.1.3
        with:
          # Artifact name
          name: Plaid.${{ env.BUILD_CONFIGURATION }}.NuGet
          # A file, directory or wildcard pattern that describes what to upload
          path: ${{ env.PROJECT_BIN }}/${{ env.BUILD_CONFIGURATION }}/*.nupkg
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
      - name: Add GitHub NuGet Source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -n github -u ${{ github.actor }} -p ${{ github.token }}
      - name: Publish to Github Packages
        run: dotnet nuget push ${{ env.PROJECT_BIN }}/${{ env.BUILD_CONFIGURATION }}/${{ env.ASSEMBLY_NAME }}.${{ env.ASSEMBLY_VERSION }}.nupkg --source "github"
      - name: Remove GitHub NuGet Source
        run: dotnet nuget remove source github
